package modelo;
// Generated 27/03/2019 02:15:07 AM by Hibernate Tools 4.3.1



/**
 * Alumno generated by hbm2java
 */
public class Alumno  implements java.io.Serializable {


     private String cveAlu;
     private String nomAlu;
     private String edaAlu;
     private String cveGru;

    public Alumno() {
    }

    public Alumno(String cveAlu, String nomAlu, String edaAlu, String cveGru) {
       this.cveAlu = cveAlu;
       this.nomAlu = nomAlu;
       this.edaAlu = edaAlu;
       this.cveGru = cveGru;
    }

    public Alumno(String edaAlu) {
        this.edaAlu = edaAlu;
    }
   
    public String getCveAlu() {
        return this.cveAlu;
    }
    
    public void setCveAlu(String cveAlu) {
        this.cveAlu = cveAlu;
    }
    public String getNomAlu() {
        return this.nomAlu;
    }
    
    public void setNomAlu(String nomAlu) {
        this.nomAlu = nomAlu;
    }
    public String getEdaAlu() {
        return this.edaAlu;
    }
    
    public void setEdaAlu(String edaAlu) {
        this.edaAlu = edaAlu;
    }
    public String getCveGru() {
        return this.cveGru;
    }
    
    public void setCveGru(String cveGru) {
        this.cveGru = cveGru;
    }




}


